StoreCrudApp/Controllers/DecimalController.cs
using Microsoft.AspNetCore.Mvc;
using StoreCrudApp.Models.OtherExampleClassesAndModels;

namespace StoreCrudApp.Controllers;

public class DecimalController : Controller
{
    [HttpGet]
    public IActionResult Index()
    {
        DecimalModel model = new() { Value = 123.12M };

 
        return View(model);
    }

    [HttpPost]
    public IActionResult Index(DecimalModel model)
    {
        if (!ModelState.IsValid)
        {
            return View(model);
        }

        return Json(model);
    }
}

StoreCrudApp/Controllers/IFormFilesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using StoreCrudApp.Models.OtherExampleClassesAndModels;

namespace StoreCrudApp.Controllers;

public class IFormFilesController : Controller
{
    private readonly string exampleImagesRootDirectory;

    public IFormFilesController(IWebHostEnvironment webHostEnvironment)
    {
        exampleImagesRootDirectory = $"{webHostEnvironment.WebRootPath}/exampleImages";
    }

    public IActionResult Index()
    {
        return View();
    }



    [HttpGet]
    public IActionResult UploadFile()
    {
        var model = new FormFileEditModel
        {
            ExistingImagePath = "/exampleImages/cat1.jpg"
        };

        return View(model);
    }

    [HttpPost]
    public async Task<IActionResult> UploadFile(FormFileEditModel model)
    {
        if (!ModelState.IsValid)
        {
            return View(model);
        }

        if (model.NewImage != null)
        {
            string filePath = Path.Combine(
                exampleImagesRootDirectory,
                model.NewImage.FileName);

            using (var stream = new FileStream(filePath, FileMode.Create))
            {
                await model.NewImage.CopyToAsync(stream);
            }

            model.ExistingImagePath = $"/exampleImages/{model.NewImage.FileName}";
        }

        return View(model);
    }





    [HttpGet]
    public IActionResult UploadFileCollection()
    {
        var model = new FormFileCollectionEditModel
        {
            ExistingImagePaths =
            [
                "/exampleImages/cat1.jpg",
                "/exampleImages/cat2.jpg",
                "/exampleImages/cat3.jpg",
            ]
        };

        return View(model);
    }

    [HttpPost]
    public async Task<IActionResult> UploadFileCollection(FormFileCollectionEditModel model)
    {
        if (!ModelState.IsValid)
        {
            return View(model);
        }

        if (model.ImagesToDelete != null && model.ImagesToDelete.Count > 0)
        {
            foreach (string imagePath in model.ImagesToDelete)
            {
                string fullPath = Path.Combine(
                    exampleImagesRootDirectory, 
                    Path.GetFileName(imagePath));

                if (System.IO.File.Exists(fullPath))
                {
                    System.IO.File.Delete(fullPath);
                }
            }
        }

        if (model.NewImages != null && model.NewImages.Count > 0)
        {
            foreach (var image in model.NewImages)
            {
                string filePath = Path.Combine(exampleImagesRootDirectory, image.FileName);

                using (var stream = new FileStream(filePath, FileMode.Create))
                {
                    await image.CopyToAsync(stream);
                }
            }
        }

        model.ExistingImagePaths = Directory
            .GetFiles(exampleImagesRootDirectory)
            .Select(file => $"/exampleImages/{Path.GetFileName(file)}")
            .ToList();


        return View(model);
    }
}

StoreCrudApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - StoreCrudApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/StoreCrudApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">StoreCrudApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-info" asp-area="" asp-controller="Decimal" asp-action="Index">Decimal form test</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-info" asp-area="" asp-controller="IFormFiles" asp-action="Index">IFormFile[Collection] form test</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - StoreCrudApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>